export const REQUEST_HAT = 'REQUEST_HAT';
export const RECIEVE_HAT = 'RECIEVE_HAT';

export const REQUEST_GLASSES = 'REQUEST_GLASSES';
export const RECIEVE_GLASSES = 'RECIEVE_GLASSES';

export const REQUEST_UPPER_CLOTHES = 'REQUEST_UPPER_CLOTHES';
export const RECIEVE_UPPER_CLOTHES = 'RECIEVE_UPPER_CLOTHES';

export const REQUEST_LOWER_CLOTHES = 'REQUEST_LOWER_CLOTHES';
export const RECIEVE_LOWER_CLOTHES = 'RECIEVE_LOWER_CLOTHES';

export const REQUEST_SHOES = 'REQUEST_SHOES';
export const RECIEVE_SHOES = 'RECIEVE_SHOES';
